wd<-getwd()
tmp<-paste(wd,"/UCI HAR Dataset",sep="")
setwd(tmp)
features<-read.table("features.txt")
activity<-read.table("activity_labels.txt")
tmp<-paste(wd,"/UCI HAR Dataset/test",sep="")
setwd(tmp)
X_test<-read.table("X_test.txt")
Y_test<-read.table("Y_test.txt")
names(X_test)<-features[,2]
data<-cbind(Y_test,X_test)
tmp<-paste(wd,"/UCI HAR Dataset/train",sep="")
setwd(tmp)
X_train<-read.table("X_train.txt")
Y_train<-read.table("Y_train.txt")
names(X_train)<-features[,2]
data1<-cbind(Y_train,X_train)
data<-rbind(data,data1)
colindex<-c(1,grep("mean",colnames(data)),grep("Mean",colnames(data)),grep("std",colnames(data)))
colindex<-sort(colindex)
data<-data[,colindex]
data<-merge(activity,data)
data$V1<-NULL
names(data)[1]<-"activity"
walking<-subset(data, activity=="WALKING")
output<-c("walking",colMeans(walking[2:87]))
walking_upstairs<-subset(data, activity=="WALKING_UPSTAIRS")
output<-rbind(output,c("walking upstairs",colMeans(walking_upstairs[2:87])))
walking_downstairs<-subset(data, activity=="WALKING_DOWNSTAIRS")
output<-rbind(output,c("walkin downstairs",colMeans(walking_downstairs[2:87])))
sitting<-subset(data, activity=="SITTING")
output<-rbind(output,c("sitting",colMeans(sitting[2:87])))
standing<-subset(data, activity=="STANDING")
output<-rbind(output,c("standing",colMeans(standing[2:87])))
laying<-subset(data, activity=="LAYING")
output<-rbind(output,c("laying",colMeans(laying[2:87])))
write.table(output, file="tidydata.txt", row.names=FALSE)